#!/bin/sh
# See https://xkcd.com/686/ -- Admin mourning

DAYS=30

USERS=`
lastlog -b $DAYS -u 3000-65533         | \
    tail -n +2                         | \
    awk '{print $1}'
`

for i in $USERS; do
    if [ ! -f /home/$i/.keep-account ]; then
	loginctl terminate-user $i
    fi
done
