#!/bin/sh
# See https://xkcd.com/686/ -- Admin mourning

DAYS=30

for range in 1000-59999 65536-4294967293; do
    for user in lastlog -b "$DAYS" -t "$(($DAYS + 2))" -u "$RANGE" | \
                  tail -n +2 | cut -d' ' -f1; do
        if [ ! -f "/home/${user}/.keep-account" ]; then
            loginctl terminate-user "$user"
        fi
    done
done
