#!/bin/bash -e
KEYRING=/var/lib/hashbang/admins.gpg

umask 002
mkdir -p   "$(dirname "${KEYRING}")"
chmod 0644 "$(dirname "${KEYRING}")"

unset GNUPGHOME
trap 'rm -rf -- "${GNUPGHOME}"' EXIT
export GNUPGHOME="$(mktemp -d)"

ADMIN_KEYS=(
    0x954A3772D62EF90E4B31FBC6C91A9911192C187A # daurnimator
    0x0A1F87C7936EB2461C6A9D9BAD9970F98EB884FD # DeviaVir
    0xC92FE5A3FBD58DD3EC5AA26BB10116B8193F2DBD # drGrove
    0xF2B7999666D83093F8D4212926CDD32189AA2885 # dpflug
    0xAE2D535ABD2E5B42CE1E97110527B4EFFB4A3AEB # kellerfuchs
    0x6B61ECD76088748C70590D55E90A401336C8AAA9 # lrvick
    0xA251FDF79171F98674EB2176FCC2D6E33BA86209 # ryan
    0x3D7C8D39E8C4DF771583D3F0A8A091FD346001CA # singlerider
)

[ ! -f "${KEYRING}" ] || gpg -q --import "${KEYRING}"
gpg -q --batch --keyserver pool.sks-keyservers.net --recv-keys "${ADMIN_KEYS[@]}"
gpg -q --batch --yes --export --export-options export-clean,export-minimal \
     -o "${KEYRING}" "${ADMIN_KEYS[@]}"
