#!/bin/sh

CONFIG="/etc/openntpd/ntpd.conf"

if [ "${METHOD}"X = "loopback"X ] || [ "${METHOD}"X = "none"X ]
then
	exit 0
fi

# Openntpd does not listen anything by default:
if ! grep -q '^[[:space:]]*listen' "$CONFIG"
then
	exit 0
fi

invoke-rc.d openntpd force-reload || true
