#!/bin/sh -e
if [ -n "$PUSH_REMOTE" ]; then
	if [ "$VCS" = git ] && [ -d .git ]; then
		for REMOTE in $PUSH_REMOTE; do
			GIT_SSH_COMMAND="ssh -o PasswordAuthentication=no" git push "$REMOTE" master
		done
	elif [ "$VCS" = hg ] && [ -d .hg ]; then
		for REMOTE in $PUSH_REMOTE; do
			hg push "$REMOTE" || true
		done
	else
		echo "PUSH_REMOTE not yet supported for $VCS" >&2
	fi
fi
